#!/usr/bin/env bash
# Generate README from lua/metaory/plugins and LSP config. Run from repo root.
set -e
cd "$(dirname "$0")/../.."
BASE="https://dotfyle.com/metaory/dotfiles-config-nvim"

plugins() { grep -rohE '"[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+"' lua/metaory/plugins 2>/dev/null | tr -d '"' | grep '\.' | sort -u; }
lsps()    { grep -rohE 'vim\.lsp\.enable\("[^"]+"\)' lua/metaory/plugins/lsp 2>/dev/null | sed 's/.*enable("\([^"]*\)").*/\1/' | sort -u; }

cat << HEADER
<div align="center">
    <img src=".github/assets/banner.png" alt="logo" width="80%">
    <h1>dotfiles/.config/nvim</h1>
</div>

<a href="$BASE"><img src="$BASE/badges/plugins?style=flat" /></a>
<a href="$BASE"><img src="$BASE/badges/leaderkey?style=flat" /></a>
<a href="$BASE"><img src="$BASE/badges/plugin-manager?style=flat" /></a>

## Install Instructions

> Install requires Neovim 0.9+. Always review the code before installing a configuration.

Clone the repository and install the plugins:

\`\`\`sh
git clone git@github.com:metaory/dotfiles ~/.config/metaory/dotfiles
NVIM_APPNAME=metaory/dotfiles/.config/nvim nvim --headless +"Lazy! sync" +qa
\`\`\`

Open Neovim with this config:

\`\`\`sh
NVIM_APPNAME=metaory/dotfiles/.config/nvim nvim
\`\`\`

## Plugins

HEADER

plugins | while read -r id; do echo "- [$id](https://dotfyle.com/plugins/$id)"; done
echo ""; echo "## Language Servers"; echo ""
lsps    | while read -r lsp; do echo "- $lsp"; done
echo ""; echo "This readme was generated by [Dotfyle](https://dotfyle.com). Regenerated by CI from \`lua/metaory/plugins\`."
