-- require("Navigator").setup({})

-- require("nightly").setup({
--   transparent = true,
--   styles = {
--     comments = { italic = true },
--     functions = { italic = false },
--     variables = { italic = false },
--     keywords = { italic = true },
--   },
--   highlights = {},
-- })
